"""empty message

Revision ID: 88baec5e29a7
Revises: 8317f0318f5f
Create Date: 2020-08-22 16:10:02.931022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88baec5e29a7'
down_revision = '8317f0318f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
